### PR TITLE
Removed wrong call to RxJavaPlugins.onError if PublishFlow.onError is called for multiple subscriptions

### LINKED ISSUE #295: Error is logged if subscribed with 2+ subscriptions and session expires
identified with #293 

## Expected behavior
No error is logged if subscribed with 2+ subscriptions and when the session expires

## Actual behavior
RxJavaPlugins.onError is called when session expires.

### Steps
1. Subscribe with stream with 2+ subscriptions
1. Expire session
1. RxJavaPlugins.onError is called by mistake

### Reproducer code
See #293 

## Details
- Affected HiveMQ MQTT Client version(s): 1.1.0, 1.0.1, 1.0.0
- Used JVM version: any

### PR DESCRIPTION
**Pull request by SgtSilvio**
**Motivation**
Resolves #295 

**Changes**
- Removed wrong call to RxJavaPlugins.onError if PublishFlow.onError is called for multiple subscriptions

### CODE REVIEW

File: src/main/java/com/hivemq/client/internal/mqtt/handler/publish/incoming/MqttIncomingPublishFlow.java [hunk 1]
```diff
@@ -92,7 +92,9 @@ public void onComplete() {
     @Override
     public void onError(final @NotNull Throwable t) {
         if (done) {
-            RxJavaPlugins.onError(t);
+            if (t != error) {
+                RxJavaPlugins.onError(t);
+            }
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/client/internal/mqtt/handler/publish/incoming/MqttIncomingPublishFlow.java]: What if this scenario occurs:
```
onError(throwable1)
onError(throwable2)
onError(throwable1)
onError(throwable2)
```

Comment (SgtSilvio) [reply src/main/java/com/hivemq/client/internal/mqtt/handler/publish/incoming/MqttIncomingPublishFlow.java]: For clarification: if a flow is registered for more than 1 subscription and all subscriptions are errored this method is called multiple times with the same throwable object.
Therefore a reference equality check is performed.
This check is actually just a safety check to detect bugs that accidentally call onError with different exceptions.
So if your described scenario occurs, there is a bug and `RxJavaPlugins.onError` is called rightly.
